### ISSUE TITLE
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting 

### ISSUE THREAD

**Issue by s-nt-s** [aws-samples/cicd-lambda-container#1]
When I deploy `templates/tooling_resources.yml` stack fail and give me this error:

Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: P93EQDAT9W9CQ1Q9; S3 Extended Request ID: TE3xAguBylAwNtqYffHuZBU8/focw2je+yV7oM2+yCCsG9bW8Ssgx39TuI+PZ+1ezc9y8bvI3vI=; Proxy: null)

**Comment by sodper** [comment]
Not sure if you've already solved it but to resolve the issue you have to add the following in your `pipeline.yml` under the `PipelineArtifactsLoggingBucket` resource:

```yaml
PipelineArtifactsLoggingBucket:
    ...
    Properties:
      ...
      OwnershipControls:
        Rules:
          - ObjectOwnership:  ObjectWriter
```
